[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "texprep"
version = "0.0.1"
dependencies = ["PyYAML>=6.0.1"]

[tool.setuptools.packages.find]
where = ["src"]
