FROM python:3.10-slim

WORKDIR /app

COPY requirements.easy.txt ./

RUN pip install --no-cache-dir -r requirements.easy.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5003", "--reload"]
